version: "3.8"

services:

  my-sba:
    image: openjdk:17
    container_name: userSerProIoT
    ports:
      - 8080:8080
      - 8000:8000
    expose:
      - "8000"
    depends_on:
      - my-db
    networks:
      - my-net
    volumes:
      - "${PWD}/build/libs/UserServiceProject-0.0.1-SNAPSHOT.jar:/app/app.jar"
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar
  my-db:
    image: mongo:5.0
    container_name: mongodbIoT
    ports:
      - 27017:27017
    networks:
      - my-net
#networks:
#  shared-net:
#    external: true
networks:
  my-net:
    driver:
      "bridge"
